FROM docker.io/node:22-alpine

WORKDIR /workspace/apps/node-demo

COPY apps/node-demo/package.json ./
COPY packages/node-email-verification/package.json ../../packages/node-email-verification/package.json

RUN npm install

WORKDIR /workspace
COPY . .

WORKDIR /workspace/apps/node-demo
ENV PORT=3000
CMD ["npm","run","dev"]

